# Generated by Django 4.0.2 on 2022-02-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorycode', models.TextField(blank=True, db_column='CategoryCode', null=True)),
                ('categorydescription', models.TextField(blank=True, db_column='CategoryDescription', null=True)),
                ('categorydisplaycode', models.TextField(blank=True, db_column='CategoryDisplayCode', null=True)),
                ('categoryid', models.IntegerField(blank=True, db_column='CategoryID', null=True)),
                ('categorydisplayindex', models.TextField(blank=True, db_column='CategoryDisplayIndex', null=True)),
                ('categorynewid', models.TextField(blank=True, db_column='CategoryNewID', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('categorylevelindex', models.TextField(blank=True, db_column='CategoryLevelIndex', null=True)),
                ('displayorder', models.TextField(blank=True, db_column='DisplayOrder', null=True)),
                ('children', models.TextField(blank=True, db_column='Children', null=True)),
                ('strinternalgroupcode', models.TextField(blank=True, db_column='strInternalGroupCode', null=True)),
                ('strorigin', models.IntegerField(blank=True, db_column='strOrigin', null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
