# Generated by Django 4.0.2 on 2022-02-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_lastname_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ansver',
            new_name='answer',
        ),
    ]
