# Generated by Django 4.0.2 on 2022-02-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_answer_inspectionsource_answer_inspectiontypes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='answer',
        ),
    ]
