# Generated by Django 4.0.3 on 2022-03-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_product_image_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_case', models.IntegerField()),
                ('InspectorName', models.TextField(blank=True, null=True)),
                ('InspectionTypes', models.TextField(blank=True, null=True)),
                ('InspectionSource', models.TextField(blank=True, null=True)),
                ('vessel', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=255, null=True)),
                ('name_case', models.TextField(max_length=255)),
                ('date_of_creation', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='InspectionSource',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='InspectionTypes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='InspectorName',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='port',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='vessel',
        ),
    ]
