# Generated by Django 4.0.3 on 2022-03-21 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_briefcase_rename_inspectionsource_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='briefcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefcase', to='main.briefcase'),
        ),
        migrations.AddField(
            model_name='briefcase',
            name='date_in_vessel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='briefcase',
            name='date_of_creation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
    ]
