# Generated by Django 4.0.3 on 2022-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_answer_briefcase_briefcase_date_in_vessel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_in_vessel',
        ),
    ]
