# Generated by Django 4.0.3 on 2022-03-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_answer_date_in_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.answer'),
        ),
    ]
