# Generated by Django 4.0.3 on 2022-03-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_image_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main.answer'),
        ),
    ]
