# Generated by Django 4.0.3 on 2022-03-23 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_image_id_alter_image_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='briefcase',
            name='id_case',
        ),
        migrations.AlterField(
            model_name='image',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.answer'),
        ),
    ]
