# Generated by Django 4.0.3 on 2022-03-23 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
