# Generated by Django 4.0.3 on 2022-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpoolnew',
            options={'managed': True},
        ),
    ]
