# Generated by Django 4.0.3 on 2022-03-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_questionpoolnew_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
