# Generated by Django 4.0.3 on 2022-07-02 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspectionsource',
            fields=[
                ('inspectionsourceid', models.AutoField(db_column='InspectionSourceId', primary_key=True, serialize=False)),
                ('majorocimfid', models.TextField(blank=True, db_column='MajorOCIMFId', null=True)),
                ('sourcename', models.TextField(blank=True, db_column='SourceName', null=True)),
                ('sourcecode', models.TextField(blank=True, db_column='SourceCode', null=True)),
                ('countrycode', models.TextField(blank=True, db_column='CountryCode', null=True)),
                ('usedid', models.TextField(blank=True, db_column='UsedId', null=True)),
                ('typecode', models.TextField(blank=True, db_column='TypeCode', null=True)),
                ('printcode', models.TextField(blank=True, db_column='PrintCode', null=True)),
            ],
            options={
                'db_table': 'InspectionSource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inspectiontypes',
            fields=[
                ('inspectiontypeid', models.AutoField(db_column='InspectionTypeId', primary_key=True, serialize=False)),
                ('inspectiontype', models.TextField(blank=True, db_column='InspectionType', null=True)),
                ('inspectioncode', models.TextField(blank=True, db_column='InspectionCode', null=True)),
                ('bitreport', models.TextField(blank=True, db_column='bitReport', null=True)),
            ],
            options={
                'db_table': 'InspectionTypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('vesselname', models.TextField(blank=True, db_column='VesselName', null=True)),
                ('vesselid', models.AutoField(db_column='VesselId', primary_key=True, serialize=False)),
                ('imo', models.TextField(blank=True, db_column='IMO', null=True)),
                ('flag', models.TextField(blank=True, db_column='FLAG', null=True)),
                ('deliverydate', models.TextField(blank=True, db_column='DeliveryDate', null=True)),
                ('grosstonage', models.TextField(blank=True, db_column='GrossTonage', null=True)),
                ('deadweight', models.TextField(blank=True, db_column='DeadWeight', null=True)),
                ('locked', models.IntegerField(blank=True, db_column='Locked', null=True)),
                ('fleetid', models.IntegerField(blank=True, db_column='FleetId', null=True)),
                ('vesselcode', models.TextField(blank=True, db_column='VesselCode', null=True)),
            ],
            options={
                'db_table': 'Vessel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnswerWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('date_of_creation', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
                ('questionid', models.TextField(blank=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('questioncode', models.TextField(blank=True, null=True)),
                ('categoryid', models.IntegerField(blank=True, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('categorynewid', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BriefcaseWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspectorName', models.TextField(blank=True, null=True)),
                ('InspectionTypes', models.TextField(blank=True, null=True)),
                ('InspectionSource', models.TextField(blank=True, null=True)),
                ('vessel', models.CharField(blank=True, max_length=255, null=True)),
                ('port', models.CharField(blank=True, max_length=255, null=True)),
                ('name_case', models.TextField(max_length=255)),
                ('date_of_creation', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
                ('date_in_vessel', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.user_directory_path)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.answerweb')),
            ],
        ),
        migrations.AddField(
            model_name='answerweb',
            name='briefcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefcaseweb', to='main.briefcaseweb'),
        ),
    ]
