# Generated by Django 4.0.3 on 2022-07-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_inspectionsource_inspectiontypes_vessel_answerweb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vettinginfo',
            fields=[
                ('inspectorname', models.TextField(blank=True, db_column='InspectorName', null=True)),
                ('inspectorsirname', models.TextField(blank=True, db_column='InspectorSirName', null=True)),
                ('port', models.TextField(blank=True, db_column='Port', null=True)),
                ('country', models.TextField(blank=True, db_column='Country', null=True)),
                ('vetdate', models.TextField(blank=True, db_column='VetDate', null=True)),
                ('vettime', models.TextField(blank=True, db_column='VetTime', null=True)),
                ('password', models.TextField(blank=True, db_column='Password', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('vesselname', models.TextField(blank=True, db_column='VesselName', null=True)),
                ('vettingcode', models.TextField(blank=True, db_column='VettingCode', null=True)),
                ('vetid', models.AutoField(db_column='VetId', primary_key=True, serialize=False)),
                ('qid', models.IntegerField(blank=True, db_column='QId', null=True)),
                ('vetgui', models.TextField(blank=True, db_column='VetGUI', null=True)),
                ('inspectiontypeid', models.IntegerField(blank=True, db_column='InspectionTypeId', null=True)),
                ('vesselid', models.IntegerField(blank=True, db_column='VesselId', null=True)),
                ('countryid', models.TextField(blank=True, db_column='CountryId', null=True)),
                ('portid', models.TextField(blank=True, db_column='PortId', null=True)),
                ('companyrepresentativename', models.TextField(blank=True, db_column='CompanyRepresentativeName', null=True)),
                ('registrationdate', models.TextField(blank=True, db_column='RegistrationDate', null=True)),
                ('majorid', models.TextField(blank=True, db_column='MajorId', null=True)),
                ('registername', models.TextField(blank=True, db_column='RegisterName', null=True)),
                ('answered', models.IntegerField(blank=True, db_column='Answered', null=True)),
                ('negative', models.TextField(blank=True, db_column='Negative', null=True)),
                ('positive', models.TextField(blank=True, db_column='Positive', null=True)),
                ('sourceid', models.TextField(blank=True, db_column='SourceId', null=True)),
                ('userid', models.TextField(blank=True, db_column='UserId', null=True)),
            ],
            options={
                'db_table': 'VettingInfo',
                'managed': False,
            },
        ),
    ]
