# Generated by Django 4.0.3 on 2022-07-04 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_vettinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageweb',
            name='answer',
        ),
        migrations.DeleteModel(
            name='AnswerWeb',
        ),
        migrations.DeleteModel(
            name='BriefcaseWeb',
        ),
        migrations.DeleteModel(
            name='ImageWeb',
        ),
    ]
